<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\entities\Bistre.Entities.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="LiteBus.Commands.Abstractions" Version="3.1.0" />
	  <PackageReference Include="LiteBus.Queries.Abstractions" Version="3.1.0" />
	</ItemGroup>

</Project>
